language: python
python:
    - "3.4"
install: python3 -m pip install -r requirements.txt
env:
    - CONFIG_PATH=blog.config.TravisConfig
before_script:
    - psql -c 'create database "blogful-test";' -U postgres
script:
  - PYTHON_PATH=. python tests/test_filters.py
  - PYTHON_PATH=. python tests/test_views_integration.py
  - PYTHON_PATH=. python tests/test_views_acceptance.py
    # Add any other tests here